server:
  port: 9090

spring:
  application:
    name: BattleByte
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://81.70.241.166:3306/battlebyte?serverTimezone=GMT%2b8
    username: root
    password: helloBattleByte
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp-mail.outlook.com
    port: 587
    username: BattleByteTeam@outlook.com
    password: HelloWorld233


mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
