server:
  port: 9090

spring:
  application:
    name: BattleByte
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://81.70.241.166:3306/battlebyte?serverTimezone=GMT%2b8
    username: root
    password: helloworld
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


emos:
  jwt:
    expire: 5
    cache-expire: 10