name: CI

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    name: Deploy Spring Boot app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build project
        run: |
          ./mvnw clean package -DskipTests

      - name: Sync to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "target/*.jar"
          target: "/home/ubuntu/BattleByte-backend"

      - name: SSH into server and start app
        run: |
          sshpass -p ${{ secrets.SERVER_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} "cd /home/ubuntu/BattleByte-backend && java -jar BattleByte.jar"